version: "3.9"

services:
  telegram-bot:
    container_name: telebot_link_GP
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /root/backup/sql:/app/backups/sql:ro 
    working_dir: /bot
    command: ["python", "main.py"]
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
